/**
 * Characters used to generate GUIDs.
 *
 * Though `\`` also can be used in Anki's GUIDs, it is not included in this table,
 * because `\`` is conflicted with the inline code syntax of Cosense.
 */
const table =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!#$%&()*+,-./:;<=>?@[]^_{|}~";

/**
 * A regular expression to match a note GUID pattern.
 *
 * @example
 * ```ts
 * import { noteGUIDRegExp } from "./core/make_note_guid";
 * import { assert } from "@std/assert/assert";
 *
 * assert(noteGUIDRegExp.test("`*8iqw@;(`"));
 * ```
 */
export const noteGUIDRegExp = /^[\w\d!#$%&()*+,\-./:;<=>?@\[\]^_{|}~]+$/;

/**
 * Generates GUID for a {@linkcode Note}.
 *
 * GUIDs generated by this function are compatible with ones generated by Anki.
 *
 * This algorithm is ported from https://github.com/ankitects/anki/blob/24.06.3/rslib/src/notes/mod.rs#L322-L343
 *
 * @returns {string} A unique identifier string for a {@linkcode Note}.
 */
export const makeNoteGUID = (): string => {
  let n = Math.min(Math.floor(Math.random() * Number.MAX_SAFE_INTEGER), 1);
  let buf = "";
  while (n > 0) {
    const q = Math.floor(n / table.length);
    const r = n % table.length;
    buf += table[r];
    n = q;
  }
  return buf.split("").reverse().join("");
};
